-- Migration: Add missing columns to hd.Carga table
-- Date: 2024
-- Purpose: Add all missing international purchase fields

-- Check if columns exist before adding them
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Invoice')
    ALTER TABLE hd.Carga ADD Invoice NVARCHAR(40) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Pedimento')
    ALTER TABLE hd.Carga ADD Pedimento NVARCHAR(30) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'ConexionesDemoras')
    ALTER TABLE hd.Carga ADD ConexionesDemoras NVARCHAR(40) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'FechaEstimDestino')
    ALTER TABLE hd.Carga ADD FechaEstimDestino DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'UltimoDiaLibre')
    ALTER TABLE hd.Carga ADD UltimoDiaLibre DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'EntregaVacio')
    ALTER TABLE hd.Carga ADD EntregaVacio DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'DiasDemoras')
    ALTER TABLE hd.Carga ADD DiasDemoras INT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'FacturaDemoras')
    ALTER TABLE hd.Carga ADD FacturaDemoras NVARCHAR(40) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'MontoUSDDemoras')
    ALTER TABLE hd.Carga ADD MontoUSDDemoras DECIMAL(12, 2) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'TCDemoras')
    ALTER TABLE hd.Carga ADD TCDemoras DECIMAL(12, 4) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'MontoDemorasMXN')
    ALTER TABLE hd.Carga ADD MontoDemorasMXN DECIMAL(12, 2) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'FacturaComercializadora')
    ALTER TABLE hd.Carga ADD FacturaComercializadora NVARCHAR(40) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'FechaDespacho')
    ALTER TABLE hd.Carga ADD FechaDespacho DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'FechaPagoPedimento')
    ALTER TABLE hd.Carga ADD FechaPagoPedimento DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Planta')
    ALTER TABLE hd.Carga ADD Planta INT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Lote')
    ALTER TABLE hd.Carga ADD Lote NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'FechaProduccion')
    ALTER TABLE hd.Carga ADD FechaProduccion DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'FechaCaducidad')
    ALTER TABLE hd.Carga ADD FechaCaducidad DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Empresa')
    ALTER TABLE hd.Carga ADD Empresa NVARCHAR(100) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Codigo')
    ALTER TABLE hd.Carga ADD Codigo NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'DescripcionProducto')
    ALTER TABLE hd.Carga ADD DescripcionProducto NVARCHAR(500) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Producto')
    ALTER TABLE hd.Carga ADD Producto NVARCHAR(200) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Marca')
    ALTER TABLE hd.Carga ADD Marca NVARCHAR(100) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Talla')
    ALTER TABLE hd.Carga ADD Talla NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Kgs')
    ALTER TABLE hd.Carga ADD Kgs DECIMAL(12, 2) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hd' AND TABLE_NAME = 'Carga' AND COLUMN_NAME = 'Cajas')
    ALTER TABLE hd.Carga ADD Cajas INT NULL;

PRINT 'Migration completed: All missing columns have been added to hd.Carga table';
